### ISSUE TITLE
SDP Unmarshal (lexer) syntax errors are unwieldy and difficult to work with

### ISSUE THREAD

**Issue by aconverse** [pion/sdp#140]
## Summary

SDP Unmarshal (lexer) syntax errors are unwieldy and difficult to work with. Let's make them easier to work with and more logable. 

## Motivation

An SDP syntax error from the lexer echoes the full SDP with "==>" "<==" cursors and doesn't actually say that it's a syntax error. As I'm sure you are well aware, an SDP can be many KB in size, making these strings absolutely enormous compared to idiomatic error strings.

Without an exported type or a well known prefix or an identifying method attache these errors, it's even hard to detect these to handle them differently in the application.

## Describe alternatives you've considered

Straw man improved error string: `syntax error: at pos 50: '='`

## Additional context

"Reduced" example: https://go.dev/play/p/ylGW1n7YBrO

```
const basicSDP = "v=0\r\n" +
	"o=jdoe 2890844526 2890842807 IN IP4 10.10.10.100\r\n" +
	"s=SDP Seminar\r\n"

func main() {
	badSDP := basicSDP + strings.Repeat("a=junk\r\n", 100)
	s := &sdp.SessionDescription{}
	err := s.Unmarshal([]byte(badSDP))
	fmt.Printf("error type: %T\n", err)
	fmt.Printf("%v\n", err)
}
```

**Comment by Sean-Der** [comment]
@aconverse I am all for that!

We have an entirely blank slate when it comes to errors so we can change them however we want :)
