### ISSUE TITLE
Any interest in a direct RFC ABNF generated Go parser???

### ISSUE THREAD

**Issue by cameronelliott** [pion/sdp#38]
## Summary

Currently the Pion SDP parser is hand generated, if it is working great, then I have little to add, 
but if people keep running into issues it might be time to use an RFC/ABNF generated parser
for Go.

https://github.com/cameron-elliott/sdp-antlr-abnf
https://github.com/cameron-elliott/sdp-antlr-abnf/tree/master/output-go

Antlr is a mature, quality parser generator.
The ABNF has been pulled from the original SDP RFCs, and hand tweaked to fix small issues.
The C# parser is being used in a commercial SIP project.

## Motivation

This is only really needed if people feel the hand parser is running into roadblocks.

A fair bit of work would still need to be done to match the current Pion data structures.

The big benefit would be one parity is reached, there would be little coding needing for parsing, really just mapping tree results into data structures.

In the end, I would say this is only useful if the current code seems like it has outlived it useful life.

**Comment by cameron-elliott** [comment]
Here is the reference abnf for SDPs:
https://github.com/cameron-elliott/sdp-antlr-abnf/blob/master/abnf-to-antlr/sdp.abnf

**Comment by Sean-Der** [comment]
Hey @cameronelliott, hopefully everything is well :) would love to get lunch again, no idea when I will be in the office again....

That is really cool! Thanks for offering, but I think the hand-rolled ones are probably better for Pion users. This is my rationale

* When debugging handwritten Go code will be easier to debug
* I need to have a good use case to overwrite code that users have contributed. I think switching out will sit at the same value, so I would feel bad :(

but thank you so much! It would be interesting to run your stuff again Pion. The compliance/interop testing would be interesting.

**Comment by cameronelliott** [comment]
@Sean-Der Totally understand, I just thought I'd mention it, in case it turned out to be useful, but maybe it is not necessary, or a nice option if the by-hand one was having issues, but the by-hand one seems to be running great!
