### ISSUE TITLE
define the RTP port range  

### ISSUE THREAD

**Issue by varadely** [pion/sdp#81]
Hello, 
I did my research in the /v3 version
Nowhere in the documentation nor in the source code I found the place to define ports for stream transports. 
The ports used are between 1024 (or maybe 16384) and 65535. 
It is common that in the use of ipbx this must be restricted.I don't know if the suggestion should be made here or in the pion/rtp project.

Thanks for everything

**Comment by Sean-Der** [comment]
Hey @varadely 

Sorry I don't fully understand. Are you trying to do a restricted port range with `pion/webrtc`? Or are we not able to craft a SDP with a port range today?

thanks!

**Comment by varadely** [comment]
Yes, I'm trying to restrict the port range for the webrtc pawn/webrtc, which is defined in the sdp, to m=audio XXXX RTP/AVP etc, where XXXX is the port that will be used for streaming.
Maybe I'm completely at odds with how it should be done. 

ty

**Comment by Sean-Der** [comment]
`pion/webrtc` doesn't support SDP munging, but we do provide an API to set the port range!

You can set it by using [SettingEngine.SetEphemeralUDPPortRange](https://pkg.go.dev/github.com/pion/webrtc/v3#SettingEngine.SetEphemeralUDPPortRange)

To see the usage of the SettingEngine check out the [custom-logger](https://github.com/pion/webrtc/tree/master/examples/custom-logger) example.

**Comment by varadely** [comment]
thank you for everything, problem solved! 
Here is the code, in case you need it (webrtc API with 2 parameters) ! 

```
	m := webrtc.MediaEngine{}
	s := webrtc.SettingEngine{
	}
	s.SetEphemeralUDPPortRange(16384, 16484)

	offer := webrtc.SessionDescription{}
	err := signal.Decode(B64, &offer)
	if err != nil {
		//DO CORRECT EXIT
		return
	}
	//DO SOME STUFF (Get payload for codec for the offer)


	api := webrtc.NewAPI(webrtc.WithMediaEngine(m), webrtc.WithSettingEngine(s))
```
