### ISSUE TITLE
Add GetFingerprint() to SessionDescription

### ISSUE THREAD

**Issue by daonb** [pion/sdp#96]
## Summary

I need to get the fingerprint of a given  sessions description.

## Motivation

I authorize clients based on their fingerprints - I need a way to get the client's fingerprint so I can check if it's in my authorized fingerprints file.

## Describe alternatives you've considered

I'm using regex do get the fingerprint directly from the description's string.

## Additional Context

There is already `WithFingerprint()` function to set the sd's fingerprint, this complements it.

**Comment by jerry-tao** [comment]
`fp,ok:=s.MediaDescriptions[0].Attribute("fingerprint")`

**Comment by daonb** [comment]
> `fp,ok:=s.MediaDescriptions[0].Attribute("fingerprint")`

Thanks!

I've tried using it instead of the regex I have now but I keep getting a `!ok`. Here's my code

```go
func GetFingerprint(sd *webrtc.SessionDescription) (string, error) {
    s, err := sd.Unmarshal()
    if err != nil {
       return "", fmt.Errorf("Failed to unmarshal sdp: %w", err)
    }

    fp, ok := s.MediaDescriptions[0].Attribute("fingerprint")
    if !ok {
         return "", fmt.Errorf("Failed to get fingerprint from sdp")
    }
    ...
```

**Comment by Sean-Der** [comment]
Hey @daonb mind trying at the global level also?

pion/webrtc does that [here](https://github.com/pion/webrtc/blob/master/sdp.go#L466-L477) 

It might be nice to add `AttributeRecursive`? This would be useful for ice as well!

**Comment by daonb** [comment]
> Hey @daonb mind trying at the global level also?
> pion/webrtc does that [here](https://github.com/pion/webrtc/blob/master/sdp.go#L466-L477) 

It works! Thanks. I've ended up using the global level `Attribute` as terminal7 has no media.
 
> It might be nice to add `AttributeRecursive`? This would be useful for ice as well!

I'd be happy to help, but I think we should find a better name as it's not really recursive. How about `CollectAttribute`?

**Comment by Sean-Der** [comment]
Closing as 'Not Planned'. 

This would be a useful helper, but I think it has some ambiguity that will make it harder to land

* What is the behavior if the attributes differ?
* Should we notify the user if was found at global or media level?
* ?

If someone is passionate about this issue I am here to help though!
